/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventory.peresepanDokter;

/**
 *
 * @author hp2k
 */
public class DetailResepPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailResepPanel
     */
    public DetailResepPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBiasa1 = new widget.PanelBiasa();
        label1 = new widget.Label();
        label2 = new widget.Label();
        label3 = new widget.Label();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        panelBiasa1.setLayout(new java.awt.GridBagLayout());

        label1.setText("label1");
        panelBiasa1.add(label1, new java.awt.GridBagConstraints());

        label2.setText("label2");
        panelBiasa1.add(label2, new java.awt.GridBagConstraints());

        label3.setText("label3");
        panelBiasa1.add(label3, new java.awt.GridBagConstraints());

        add(panelBiasa1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Label label1;
    private widget.Label label2;
    private widget.Label label3;
    private widget.PanelBiasa panelBiasa1;
    // End of variables declaration//GEN-END:variables
}
