/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package inventory;

import event.EventBus;
import event.eventList.AturanPakaiSelectedEvent;
import fungsi.WarnaTable2;
import fungsi.koneksiDB;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;

class AturanPakaiTableModel extends AbstractTableModel {

    ArrayList<String> aturanPakai;
    Connection koneksi = koneksiDB.condb();

    final String[] COLUMN = new String[]{
        "Aturan Pakai"
    };

    public AturanPakaiTableModel() throws SQLException {
        aturanPakai = new ArrayList();

        PreparedStatement st = koneksi.prepareStatement("SELECT * FROM master_aturan_pakai");
        ResultSet rs = st.executeQuery();

        while (rs.next()) {
            aturanPakai.add(rs.getString(1));
        }

    }

    public void create(String nama) throws SQLException {
        PreparedStatement st = koneksi.prepareStatement("INSERT INTO master_aturan_pakai VALUES (?)");
        st.setString(1, nama);

        final int result = st.executeUpdate();
        if (result > 0) {
            this.aturanPakai.add(nama);
            this.fireTableRowsInserted(this.aturanPakai.size() - 1, this.aturanPakai.size() - 1);
        }
    }

    public void delete(int rowIndex) throws SQLException {

        PreparedStatement st = koneksi.prepareStatement("DELETE FROM master_aturan_pakai WHERE aturan = ?");
        st.setString(1, this.aturanPakai.get(rowIndex));

        final int result = st.executeUpdate();

        if (result > 0) {
            this.aturanPakai.remove(rowIndex);
            this.fireTableRowsDeleted(rowIndex, rowIndex);
        }
    }

    public String getRow(int rowIndex) {
        return this.aturanPakai.get(rowIndex);
    }

    @Override
    public int getRowCount() {
        return this.aturanPakai.size();
    }

    @Override
    public int getColumnCount() {
        return COLUMN.length;
    }

    @Override
    public String getColumnName(int column) {
        return COLUMN[column];
    }

    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {
        return aturanPakai.get(rowIndex);
    }

}

/**
 *
 * @author hp2k
 */
public class DlgAturanPakaiCom extends javax.swing.JDialog {

    private AturanPakaiTableModel tmdlAturanPakai;
    private java.awt.Dialog parent;
    private EventBus bus;

    /**
     * Creates new form DlgAturanPakaiCom
     */
    public DlgAturanPakaiCom(java.awt.Dialog parent, boolean modal, EventBus bus) {
        super(parent, modal);
        this.parent = parent;
        this.bus = bus;
        initComponents();

        try {
            tmdlAturanPakai = new AturanPakaiTableModel();
            tblAturanPakai.setModel(tmdlAturanPakai);
            tblAturanPakai.setDefaultRenderer(java.lang.Object.class, new WarnaTable2(1));
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public DlgAturanPakaiCom(java.awt.Dialog parent, boolean modal) {
        this(parent, modal, new EventBus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        internalFrame1 = new widget.InternalFrame();
        panelBiasa1 = new widget.PanelBiasa();
        tbAturanPakai = new widget.TextBox();
        label1 = new widget.Label();
        panelBiasa3 = new widget.PanelBiasa();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAturanPakai = new widget.Table();
        panelBiasa4 = new widget.PanelBiasa();
        label2 = new widget.Label();
        tbCariAturanPakai = new widget.TextBox();
        btnCari = new widget.Button();
        btnSimpan = new widget.Button();
        btnHapus = new widget.Button();
        btnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "::[Aturan Pakai]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        panelBiasa1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        panelBiasa1.setLayout(new java.awt.GridBagLayout());

        tbAturanPakai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAturanPakaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelBiasa1.add(tbAturanPakai, gridBagConstraints);

        label1.setText("Aturan Pakai");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelBiasa1.add(label1, gridBagConstraints);

        internalFrame1.add(panelBiasa1, java.awt.BorderLayout.PAGE_START);

        panelBiasa3.setLayout(new javax.swing.BoxLayout(panelBiasa3, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblAturanPakai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAturanPakai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAturanPakaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAturanPakai);

        panelBiasa3.add(jScrollPane1);

        internalFrame1.add(panelBiasa3, java.awt.BorderLayout.CENTER);

        panelBiasa4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        panelBiasa4.setLayout(new java.awt.GridBagLayout());

        label2.setText("Keywords");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 10);
        panelBiasa4.add(label2, gridBagConstraints);

        tbCariAturanPakai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCariAturanPakaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        panelBiasa4.add(tbCariAturanPakai, gridBagConstraints);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelBiasa4.add(btnCari, gridBagConstraints);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        btnSimpan.setMnemonic('S');
        btnSimpan.setToolTipText("Alt+S");
        btnSimpan.setPreferredSize(new java.awt.Dimension(28, 23));
        panelBiasa4.add(btnSimpan, new java.awt.GridBagConstraints());

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        btnHapus.setMnemonic('H');
        btnHapus.setToolTipText("Alt+H");
        btnHapus.setPreferredSize(new java.awt.Dimension(28, 23));
        panelBiasa4.add(btnHapus, new java.awt.GridBagConstraints());

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        btnKeluar.setMnemonic('4');
        btnKeluar.setToolTipText("Alt+4");
        btnKeluar.setPreferredSize(new java.awt.Dimension(28, 23));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        panelBiasa4.add(btnKeluar, gridBagConstraints);

        internalFrame1.add(panelBiasa4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCariAturanPakaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCariAturanPakaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCariAturanPakaiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbAturanPakaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAturanPakaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbAturanPakaiActionPerformed

    private void tblAturanPakaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAturanPakaiMouseClicked
        if (tblAturanPakai.getSelectedRow() < 0 || evt.getButton() != MouseEvent.BUTTON1 || evt.getClickCount() != 2) {
            return;
        }

        this.bus.publish(new AturanPakaiSelectedEvent(tmdlAturanPakai.getRow(this.tblAturanPakai.getSelectedRow())));

        dispose();

    }//GEN-LAST:event_tblAturanPakaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAturanPakaiCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAturanPakaiCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAturanPakaiCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAturanPakaiCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAturanPakaiCom dialog = new DlgAturanPakaiCom(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button btnCari;
    private widget.Button btnHapus;
    private widget.Button btnKeluar;
    private widget.Button btnSimpan;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private widget.Label label1;
    private widget.Label label2;
    private widget.PanelBiasa panelBiasa1;
    private widget.PanelBiasa panelBiasa3;
    private widget.PanelBiasa panelBiasa4;
    private widget.TextBox tbAturanPakai;
    private widget.TextBox tbCariAturanPakai;
    private widget.Table tblAturanPakai;
    // End of variables declaration//GEN-END:variables
}
